convMatrix:
- - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.2
  - 0.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 0.2
  - 0.5
  - 0.2
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 0.2
  - 0.5
  - 0.8
  - 0.5
  - 0.2
  - 0.0
  - 0.0
- - 0.0
  - 0.2
  - 0.5
  - 0.8
  - 1.0
  - 0.8
  - 0.5
  - 0.2
  - 0.0
- - 0.0
  - 0.0
  - 0.2
  - 0.5
  - 0.8
  - 0.5
  - 0.2
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 0.2
  - 0.5
  - 0.2
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.2
  - 0.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
xLen: 5
yLen: 5