BMs:
- ID: 3135124191
  difficulty: BM
  name: CsLevel.hartrean.AAT 1W2T.S6YNHL
  scores: []
  size: 0.65R
  x: 0
  y: -1
- ID: 3135123594
  difficulty: BM
  name: CsLevel.hartrean.AAT 1W2T.S6YNGY
  scores: []
  size: 0.45R
  x: 1
  y: -1
- ID: 3135123412
  difficulty: BM
  name: CsLevel.hartrean.AAT 1W2T.S6YNEL
  scores: []
  size: 0.3R
  x: 2
  y: -1
- ID: 3135123274
  difficulty: BM
  name: CsLevel.hartrean.AAT 1W2T.S6YNDF
  scores: []
  size: 0.2R
  x: 3
  y: -1
- ID: 3135118570
  difficulty: BM
  name: CsLevel.hartrean.AAT 1W2T.S6YLZC
  scores: []
  size: 0.14R
  x: 4
  y: -1
trainers:
- - ID: 3135123147
    difficulty: 3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YN8Q
    size: 0.65R
    x: 0
    y: 0
  - ID: 3135122923
    difficulty: 3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YN7O
    size: 0.45R
    x: 1
    y: 0
  - ID: 3135122783
    difficulty: 3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YN6O
    size: 0.3R
    x: 2
    y: 0
  - ID: 3135122583
    difficulty: 3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YN5S
    size: 0.2R
    x: 3
    y: 0
  - ID: 3135124418
    difficulty: 3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YLL8
    size: 0.14R
    x: 4
    y: 0
- - ID: 3135122423
    difficulty: 2.575S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMZT
    size: 0.65R
    x: 0
    y: 1
  - ID: 3135122077
    difficulty: 2.575S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMXW
    size: 0.45R
    x: 1
    y: 1
  - ID: 3135121811
    difficulty: 2.575S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMWY
    size: 0.3R
    x: 2
    y: 1
  - ID: 3135121589
    difficulty: 2.575S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMW3
    size: 0.2R
    x: 3
    y: 1
  - ID: 3135117655
    difficulty: 2.575S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YLP8
    size: 0.14R
    x: 4
    y: 1
- - ID: 3135121360
    difficulty: 2.15S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMQY
    size: 0.65R
    x: 0
    y: 2
  - ID: 3135121047
    difficulty: 2.15S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMP1
    size: 0.45R
    x: 1
    y: 2
  - ID: 3135120866
    difficulty: 2.15S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMO1
    size: 0.3R
    x: 2
    y: 2
  - ID: 3135120739
    difficulty: 2.15S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMN5
    size: 0.2R
    x: 3
    y: 2
  - ID: 3135118261
    difficulty: 2.15S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YLST
    size: 0.14R
    x: 4
    y: 2
- - ID: 3135120519
    difficulty: 1.725S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMIB
    size: 0.65R
    x: 0
    y: 3
  - ID: 3135120235
    difficulty: 1.725S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMHC
    size: 0.45R
    x: 1
    y: 3
  - ID: 3135119782
    difficulty: 1.725S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMG3
    size: 0.3R
    x: 2
    y: 3
  - ID: 3135119652
    difficulty: 1.725S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMEN
    size: 0.2R
    x: 3
    y: 3
  - ID: 3135118423
    difficulty: 1.725S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YLXD
    size: 0.14R
    x: 4
    y: 3
- - ID: 3135119499
    difficulty: 1.3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YMAN
    size: 0.65R
    x: 0
    y: 4
  - ID: 3135119323
    difficulty: 1.3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YM9R
    size: 0.45R
    x: 1
    y: 4
  - ID: 3135119177
    difficulty: 1.3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YM91
    size: 0.3R
    x: 2
    y: 4
  - ID: 3135118742
    difficulty: 1.3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YM7T
    size: 0.2R
    x: 3
    y: 4
  - ID: 3135113746
    difficulty: 1.3S
    lockVal: -1
    name: CsLevel.hartrean.AAT 1W2T.S6YM4Z
    size: 0.14R
    x: 4
    y: 4


